# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LootType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('defense', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Cell')),
            ],
        ),
        migrations.RemoveField(
            model_name='hp',
            name='cell',
        ),
        migrations.AddField(
            model_name='character',
            name='attack',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='defense',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HP',
        ),
    ]
