# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20160331_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=15)),
                ('item_stats', models.IntegerField()),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.LootType')),
            ],
        ),
    ]
