# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_loot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('inv_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Loot')),
                ('inv_coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Cell')),
            ],
        ),
    ]
