# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Loot')),
                ('inv_coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Cell')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='inv_content',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='inv_coord',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
