# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20160331_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Character')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Loot')),
            ],
        ),
    ]
