# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_inventorycharacter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.InventoryCharacter')),
                ('slot_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.LootType')),
            ],
        ),
    ]
