# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20160401_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotcharacter',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.InventoryCharacter'),
        ),
    ]
